prefer /lib64/security on 64-bit platforms

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19131,8 +19131,11 @@ echo $ECHO_N "checking for PAM directory... $ECHO_C" >&6
 test "$PAM_MODDIR" = "no"  && { { echo "$as_me:$LINENO: error: PAM support is required" >&5
 echo "$as_me: error: PAM support is required" >&2;}
    { (exit 1); exit 1; }; }
-test "$PAM_MODDIR" = "yes" && PAM_MODDIR="/lib/security"
-test -d "$PAM_MODDIR"      || { { echo "$as_me:$LINENO: error: $PAM_MODDIR not found" >&5
+if test "$PAM_MODDIR" = "yes"; then
+        PAM_MODDIR="/lib64/security"
+    test -d "$PAM_MODDIR" || PAM_MODDIR="/lib/security"
+fi
+test -d "$PAM_MODDIR" || { { echo "$as_me:$LINENO: error: $PAM_MODDIR not found" >&5
 echo "$as_me: error: $PAM_MODDIR not found" >&2;}
    { (exit 1); exit 1; }; }
 echo "$as_me:$LINENO: result: $PAM_MODDIR" >&5
